version: 2
updates:
  - package-ecosystem: npm
    directory: /server
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: Europe/Copenhagen
    open-pull-requests-limit: 3
    groups:
      server-deps:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /client
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: Europe/Copenhagen
    open-pull-requests-limit: 3
    groups:
      client-deps:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: Europe/Copenhagen
    open-pull-requests-limit: 3
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: Europe/Copenhagen
    open-pull-requests-limit: 3
    groups:
      docker:
        patterns: ["*"]
